default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: legit_news_test

production:
  <<: *default
  database: legit_news_prod
  username: legit_news_prod
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
